[package]
name = "dependabot-cargo-bin-test"
version = "0.1.0"
authors = ["calebcartwright"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
